# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 547a6fc2d9c88a9705f5a4eede400be4e2fa1569049f80d725c1d636d881f1fda5f07fa68c372dade3431fcf618ace66657b8f693739dfe494d7648914a274fc

test:
  secret_key_base: 0f7d2c7fe1d1367ec65c0405d903c1373d6a68367f9f5e539f47c7f1204537c0e9a82987db7b30a591acc786c5c7fc66fd4963014e121398d978688b090cfde3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
